# Generated by Django 4.2.7 on 2023-11-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('category', models.IntegerField()),
                ('rarity', models.CharField(max_length=4)),
                ('theme', models.IntegerField()),
                ('tag', models.CharField(max_length=30)),
                ('episode', models.IntegerField()),
                ('point', models.IntegerField()),
                ('size', models.IntegerField()),
                ('atk', models.IntegerField()),
                ('defs', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('limit', models.IntegerField()),
                ('frame', models.CharField(max_length=30)),
                ('collect', models.BooleanField()),
                ('desc', models.TextField()),
                ('skill_turn', models.TextField()),
                ('skill_instance', models.TextField()),
                ('skill_attack', models.TextField()),
                ('skill_defend', models.TextField()),
                ('link', models.CharField(max_length=40)),
                ('producible', models.BooleanField()),
            ],
            options={
                'ordering': ['category', 'theme', 'episode', 'point'],
            },
        ),
    ]
